# ---------------------------------------------
#                   Messages
# ---------------------------------------------
messages:
  welcome: 'Bienvenue sur ce serveur tout simplement incroyable'
  salut: 'Comment ils vont les gens'

# ---------------------------------------------
#                     SQL
# ---------------------------------------------
#
# with userSQL = false | true you can choose if you want a db or not
#
# ---------------------------------------------
useSQL: false
tablename: "viazel"
host: "this his your host"
password: "your password"
user: "your user"
dbname: "The name of your database"
port: 3306
