# ---------------------------------------------
#                   Messages
# ---------------------------------------------
messages:
  welcome: "&aBienvenue sur ce serveur tout simplement incroyable"
  permission-denied: "&c» Vous n'avez pas le droit d'utiliser la commande {command}"
  spawn: "&a» Vous vous êtes téléporté au spawn !"
  setspawn: "&a» Vous avez définie la position du spawn !"
  feed: "&a» Vous avez été rassasié !"

# ---------------------------------------------
#                     SQL
# ---------------------------------------------
#
# with userSQL = false | true you can choose if you want a db or not
#
# ---------------------------------------------
useSQL: false
host: "this his your host"
user: "your user"
password: "your password"
dbname: "The name of your database"
tablename: "viazel"
port: 3306